### ISSUE TITLE
PLS HELP CREATING A TRASFORMER ROLE

### ISSUE THREAD

**Issue by TechDevOfficial** [DillyzThe1/DillyzRoleApi-Rewritten#4]
How to make transform button and it transform in another sprite?

**Comment by DillyzThe1** [comment]
If you are seeking help in creating an Among Us mod, you should not abuse the issues page by telling people to walk you through making a mod in all caps, as that can be seen as severely disrespectful. 
You should be using this page to ask about how something in the API works or to report a bug directly to me. You may also request API features and whatnot.

Mod ideas and dev discussion prefferably belong to the [Discord Server](https://discord.gg/49NFTwcYgZ), though.
As for making a button, go through the [full setup tutorial](https://github.com/DillyzThe1/DillyzRoleApi-Rewritten/wiki/The-Basics) and refer to both the [role setup guide]() alongside the [role button example](https://github.com/DillyzThe1/DillyzRoleApi-Rewritten/wiki/Code-Samples#kill-button).

Once you've figured that out (or if you have questions about the guides, as they're pretty outdated), you may come to the aforementioned discord server and discuss your mod's progress and your intent to change the button functionality.



I would fully recommend knowing about using Unity Engine prior to modding a game within it, though.

**Comment by TechDevOfficial** [comment]
I  don’t receive any help in the server Inviato da Posta per Windows Da: DillyzThe1Inviato: lunedì 3 aprile 2023 16:32A: DillyzThe1/DillyzRoleApi-RewrittenCc: TechDev; AuthorOggetto: Re: [DillyzThe1/DillyzRoleApi-Rewritten] PLS HELP CREATING A TRASFORMER ROLE (Issue #4) If you are seeking help in creating an Among Us mod, you should not abuse the issues page by telling people to walk you through making a mod in all caps, as that can be seen as severely disrespectful.You should be using this page to ask about how something in the API works or to report a bug directly to me. You may also request API features and whatnot.Mod ideas and dev discussion prefferably belong to the Discord Server, though.As for making a button, go through the full setup tutorial and refer to both the role setup guide alongside the role button example.Once you've figured that out (or if you have questions about the guides, as they're pretty outdated), you may come to the aforementioned discord server and discuss your mod's progress and your intent to change the button functionality.I would fully recommend knowing about using Unity Engine prior to modding a game within it, though.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
